### PR TITLE
fix: get_children should not break supervision tree integrity

### LINKED ISSUE #310: ActorRef::get_children() clears children record from supervision tree
**Describe the bug**

I'm not sure if this is intentional, but it's definitely a footgun. If I call `some_actor.get_children()` twice, then the second time returns an empty Vec. The children actors are still running and points to the original parent (half unlinked).

**To Reproduce**
1. Create an actor tree
2. On root actor, call `root.get_children()`
3. `assert_eq!(first_children_len, second_children_len)`

**Expected behavior**

There should be a  non-destructive way to retrieve the list of children actors.

**Additional context**

https://github.com/slawlor/ractor/blob/main/ractor/src/actor/supervision.rs#L140

### PR DESCRIPTION
**Pull request by kanru**
This fixes #310 

Please suggest where and what tests I can add.

### CODE REVIEW

File: ractor/src/actor/supervision.rs [hunk 1]
```diff
@@ -134,15 +134,21 @@ impl SupervisionTree {
         }
     }
 
-    pub(crate) fn get_children(&self) -> Vec<ActorCell> {
+    pub(crate) fn take_children(&self) -> Vec<ActorCell> {
```
Comment (slawlor) [inline ractor/src/actor/supervision.rs:137]: we shouldn't need a take method anywhere, the supervision tree should only be modified upon link/unlink. This should be as easy as just replacing the functionality inside with the non-clearing version, and updating a test case to make sure that the supervision tree isn't modified.

#310 is indeed a bug, and fixing it vs adding a new API like this is better for footgun safety.

Comment (kanru) [reply ractor/src/actor/supervision.rs:137]: I think some kind of clearing is still required. Initially I just removed the `clear()` but then the double-link test run out of stack. I realized if we don't clear the children list after unlink, we can run into mutual recursion in the double-link scenario. So instead of calling `clear()` everywhere I created the take method.

**Comment by slawlor** [comment]
Check out this commit. Feel free to pull it on top and update your PR

62efc4310fa85b6670837fd89ace42478263dbac

**Review by slawlor — APPROVED** [review]
Looks great, thanks!
